/**
 * 自动生成的解法文件 (Merged & Optimized)
 * 
 * Data Sources:
 * [W2]      : Weight=2.0, Pruning=OFF (倾向最优解，但容易超时)
 * [W3-Deep] : Weight=3.0, MaxNodes=20M, Pruning=ON (平衡且深度大，解决复杂关卡)
 * [W5]      : Weight=5.0, Pruning=ON (极速，解决超长关卡)
 * 
 * Selection Logic: Shortest path length > Lower Weight
 */

const AUTO_SOLVED_PATHS = {
  carrot: {
    // [Length: 29] Source: [W2]
    0: "UUUUULDDRRUULDDDDLLLUUUUUURRR",
    // [Length: 21] Source: [W2]
    1: "UUUUUULLDDRRRRUULLUUU",
    // [Length: 25] Source: [W2]
    2: "UUUULUULDDRURRURDDLUULUUU",
    // [Length: 60] Source: [W3-Deep]
    3: "RUUUURRURDDRUUDDLLRRURRURDDRUUDDLLRDDDDLUURRDDLLULLULLDDRRUL",
    // [Length: 50] Source: [W3-Deep]
    4: "UUUULUULDDULLLLUUUURRRRRRDDDRDDRUUDRRRRUUUULLLLLUL",
    // [Length: 57] Source: [W3-Deep]
    5: "RRRRRRURRDDLLUULUURRRRUURUURDDLLLLLLLUULDDULLLUUUURRRRRRR",
    // [Length: 80] Source: [W3-Deep]
    6: "UUUUULDUURUUUUULDDUURRDRRRURDURDRRRURDRUDDLDDDDRUDDLDDDDDRUUDDLLULLLDLUDLUURUUUU",
    // [Length: 31] Source: [W3-Deep]
    7: "URUURRRRDDRUURRDDLDDLULLLLLUUUL",
    // [Length: 42] Source: [W3-Deep]
    8: "ULDDRRUUDRURDDRUUDDLLRDDDDDLUURRDDULLLLLLL",
    // [Length: 46] Source: [W2] - W3 为 46 但 W2 权重更低
    9: "DLRRUULULLLUUUURDDUUUURRDDDDDRRRUUUULDDUUUUULL",
    // [Length: 61] Source: [W2]
    10: "DLRRUULUUUUUUUULLLRRRRRRLLLDDLLDDLUDDDRRRRRRRRRRRRUUUDLUULLUU",
    // [Length: 73] Source: [W3-Deep]
    11: "RRURURRUURDDDDDLUURRDDUULLLLURRRURUDDLDDDLLLLDDDRRRDDDRUUURDDDURRRUUUUUUR",
    // [Length: 56] Source: [W2]
    12: "DDDDRRRRUUUUUUUURRRRDDDDLLLLLLLDLDDDRRRRUUUUUUUURRRRDDDD",
    // [Length: 80] Source: [W2]
    13: "DDDDRRRLLLUUUUUUUURRRRLRUDRRRLLLDUDDDDDDDDRRRRUUUUUUUUUUULLLLDDDLLLLDDDDRRRRRRRR",
    // [Length: 46] Source: [W2]
    14: "RRRRLRUURRRLRUDRRRURDDRUUDDLLRDLLDDRLDULDLLLLL",
    // [Length: 74] Source: [W2]
    15: "RRULUUUUULDDRRURURLDDRRRDDDLUURRRDDLDLLUURRUUUUDLLLLDDLUURLLDDRRDDULDLDL",
    // [Length: 81] Source: [W2] - 比 W3 (83) 更短
    16: "DDDDDLURRLLULUULLUURRDRRURUUUULDRURDDLDDDLLLRRRRRRRURRDDLLDDLLDDULLULDLRURDRRURDR",
    // [Length: 124] Source: [W2] - 仅 W2 解出
    17: "RDRRRURLDLLLUULUUULDRRUUULDRRRRRUURUUURRRRDRULLLLLDDDRRRRDRLDULRUDRDLLUULLLUUULLLDLLURRRRRRRRDULLLDDDLLDLLLDDLDDDDRDRRRURRRR",
    // [Length: 76] Source: [W2]
    18: "RRLUURRRRRRDDDDLLLLLLUURRRRRRRRRRRUUUUUULLLDDDRRULURLDRDLLUUURRRDDDDDDLLDDDR",
    // [Length: 54] Source: [W2] - 仅 W2 解出
    19: "LLLUUUUUDDRRLLUUUUUURRRRRRDDDDDUULLLLLRRDDDRRRDDDLLLDD",
    // [Length: 75] Source: [W2]
    20: "URRRRRRRRUURRUUUUURRDDDDDDLLLLUUUUULLLLLLLLURRDDDDDRUUDDRUUUUURRDDDDDDDDRRR",
    // [Length: 112] Source: [W2] - 仅 W2 解出
    21: "DRRLLLDDDUUULLLLLULRURRDURRUURDDDRRRRRRLLLLUURRRULUURRDLDRLDRLLLLDDRRRLLLDULLDDDUUURRDDDUUUUURRRLLLLLUUUUDULUULL",
    // [Length: 181] Source: [W2]
    22: "UUUUURRDURRRLLDUDULDDRRDDLRULUURUUURRRRRUURUURDDRUULLLLDLLLLLLLLDDDRRDDRRRLULLLULUUURRRRRRRRRDDDRDDDDDLUUULDDDRRRULDDUUUURDULUULLLLRRRUULLLULLLLLLDDDDDDRURDULDRLDULURRRRRLLLLDRLDDLD",
    // [Length: 68] Source: [W2]
    23: "UULUUULRRLRURRRRDULLDDDDLUURUURDLLLDULLLLLLLUDULURRRRDLDDUDRDLLLLUUL",
    // [Length: 228] Source: [W3-Deep] - 仅 W3-20M 解出 (超难)
    24: "DDDDDDRLUURRRLLLUURLDDDDRRRLLLUUUURRRRUURRRRRDDDDDDLLLULUDDUURUUUURRRDULUUDDLLLLLLLLUUDDRRRURLRUULUUURRLRUDRLRRDDDLDDRDLLLLLDDDDDDRRLLUUUUUURRRRRRRRRRRRULLLUULDDDDDLLLLLLLLUUUUDDDDRRRURUUUDDDRDRRR",
    // [Length: 168] Source: [W2] - 仅 W2 解出
    25: "DDDDUUUULLDDDDDDDURRDDDDDDLLUUUUDULLUUUUUUUULLDDDUUURRRRRRRRDDUURRDDDDDDDDDDDUUUUUUUUUUURRDDDDDDDDDDDDUUUUULLLLDDDDDUUUUUUUUUUUULLLLLLDDDDDDDDDDDDUUUUUUUUUUUULLDDDDDDDDDDDD",
    // [Length: 92] Source: [W2]
    26: "LDDRRDUDRLDDLLLULLLLLLLDDDDDDRRRUDRUULRURRRRRLLLLLLDULURRLLDRDDDRUDRLRRRLLLRRRLLLRLDDLULLLUL",
    // [Length: 94] Source: [W2]
    27: "LLLLLUUDULRUDRRRRRRRRRRDDLLLLUULLLLLLDULLLUURRRUUUURRRRRRRRRRDDDLLLULDDLUUDDRRLULLLLDDDUDRRRRR",
    // [Length: 94] Source: [W3-Deep] - 仅 W3-20M 解出
    28: "DRRRRRRULRULUUUUURDRRRRUDRDDDDLLLLDDDDDLLLLLUULLLUDDRUDRRUUUULLUURDLLDUURURRRRURRLRUDRRRRLRUULLDDD",
    // [Length: 82] Source: [W2]
    29: "LLDUDDDDDRRRRRRRRUUUDLLLLLLLLLLUDLLUUUUDDDDRRUUUDDDRRUUURRURRDDRLDDDDRRRRUUUULRUUU",
  },
  egg: {
    // [Length: 26] Source: [W2]
    0: "DLLDDDDDDRUUURDRURDDDLULDU",
    // [Length: 41] Source: [W2]
    1: "DLLDLDRLDRLDLDRRRRRRLRULLLLLDLDRLDRLDRLDDR",
    // [Length: 66] Source: [W3-Deep] - W2 未解出
    2: "DDDRDDRRRUDRULLLURUURLDRLRLUURRRDDLLRLDULUULLDDLDDDLULLDRDLDRRRURD",
    // [Length: 72] Source: [W2] - 远短于 W5 (116)
    3: "LUDDURULRLDULLURRUDRRUDRRDRRURDDDDDLRLDULRLDDLLLDULLDDLLDLUDULRUURUURURR",
    // [No Solution]
    4: "",
    // [No Solution]
    5: "",
    // [No Solution]
    6: "",
    // [Length: 98] Source: [W3-Deep] - 比 W2 (112) 短
    7: "UURLDDRRRRRRRRRRUDRRUUUUUUUUUULLLLLLLLDDDURRDDRLLLDDRRUDRRUUUURRDDDDDLLUDLLLLLLUUUUUUUUUURRRRRRRRRR",
    // [Length: 132] Source: [W3-Deep] - 比 W2 (138) 短
    8: "RRUUUUUULLDDDDDDRRRRRRUUUDRRRRRRUUUULRUUUUUULLLLLLDULLLLLLDDRRRRRRDDLLLLLDDDDDDDDRRRRUUUUUULRRRUDRLDDRRRRRUUUUUUUULLLLDDDDDRRUUUUUURR",
    // [Length: 112] Source: [W2]
    9: "URRLLUUUUDDDDRRRLLDDRDRRDULLDDDUUURRDDDDUUUUURRDDDDUUUULLLLLUURRRRLLLLDDLLDDULLDDDUUURRDDDUUULLLLDDDUUURRRURUULL",
    // [Length: 157] Source: [W2]
    10: "LLLDLULLLDLDUULLLDDULLDDDDDDDRRRRRUULRUUULLLDDDLLDDDRRDDRRRDRRRRUUUUUUUUURDDDDDDDDDRRRUUUUUUUULLLLLLURRRRRRUUULLLLLLLLLLLDLLDDDDDDDDRRDDRRRDRUDULRUURRRRRULLLLL",
    // [Length: 77] Source: [W3-Deep] - W2 未解出
    11: "DDLUUURRDDDDDDRRLLDLDLDDLLULULULDLUULLDRDLDRRRDRRUUUURRRUURRLDDRULRUDRRDDDLLL",
    // [Length: 73] Source: [W2]
    12: "URURRUURUUULLULDDRDLLLLLLULUURDRDDDRUUUUUULDDLULURUULLDLLDDLDDDDDDDDRDRRR",
    // [Length: 115] Source: [W2]
    13: "DRRRRDDDDRRDDDDDLLLLLUULLLLLUUUULLUUUUURRRRRDDRDDRDLLULDDDRURRURDDLLDDRRRRUUUURRUUUUULLLLLDDLLLLLDDDDLLDDDDDRRRRRUR",
    // [Length: 122] Source: [W2] - 仅 W2 解出
    14: "UURRRLDDRLUULLDDDDRRRRRDDLLLLLLLLLLUURUDRUUULLUURRRRUURRUUULLLLDLULDDRRRUDRUDRLDDDDDDDDDRUUUUURDDDLLDDDLLLUUUUUUUURRRRURRRRUURRDDURURRDDDLL",
    // [No Solution]
    15: "",
    // [No Solution]
    16: "",
    // [No Solution]
    17: "",
    // [No Solution]
    18: "",
    // [No Solution]
    19: "",
  }
};