/**
 * 自动生成的解法文件 (Merged from 3 configurations)
 * 
 * 来源配置说明:
 * [Cfg1]: Weight=3.0, MaxNodes=4M, Pruning=ON  (平衡)
 * [Cfg2]: Weight=2.0, MaxNodes=4M, Pruning=OFF (追求更短路径)
 * [Cfg3]: Weight=5.0, MaxNodes=4M, Pruning=ON  (追求极速/死局突破)
 */

const AUTO_SOLVED_PATHS = {
  carrot: {
    // [Length: 29] Source: [Cfg2]
    0: "UUUUULDDRRUULDDDDLLLUUUUUURRR",
    // [Length: 21] Source: [Cfg2]
    1: "UUUUUULLDDRRRRUULLUUU",
    // [Length: 25] Source: [Cfg2]
    2: "UUUULUULDDRURRURDDLUULUUU",
    // [Length: 60] Source: [Cfg1]
    3: "RUUUURRURDDRUUDDLLRRURRURDDRUUDDLLRDDDDLUURRDDLLULLULLDDRRUL",
    // [Length: 50] Source: [Cfg1]
    4: "UUUULUULDDULLLLUUUURRRRRRDDDRDDRUUDRRRRUUUULLLLLUL",
    // [Length: 57] Source: [Cfg1]
    5: "RRRRRRURRDDLLUULUURRRRUURUURDDLLLLLLLUULDDULLLUUUURRRRRRR",
    // [Length: 80] Source: [Cfg1]
    6: "UUUUULDUURUUUUULDDUURRDRRRURDURDRRRURDRUDDLDDDDRUDDLDDDDDRUUDDLLULLLDLUDLUURUUUU",
    // [Length: 31] Source: [Cfg1]
    7: "URUURRRRDDRUURRDDLDDLULLLLLUUUL",
    // [Length: 42] Source: [Cfg1]
    8: "ULDDRRUUDRURDDRUUDDLLRDDDDDLUURRDDULLLLLLL",
    // [Length: 46] Source: [Cfg2] - 比 Cfg1 短
    9: "DLRRUULULLLUUUURDDUUUURRDDDDDRRRUUUULDDUUUUULL",
    // [Length: 61] Source: [Cfg2]
    10: "DLRRUULUUUUUUUULLLRRRRRRLLLDDLLDDLUDDDRRRRRRRRRRRRUUUDLUULLUU",
    // [Length: 73] Source: [Cfg1] - Cfg2 未解出
    11: "RRURURRUURDDDDDLUURRDDUULLLLURRRURUDDLDDDLLLLDDDRRRDDDRUUURDDDURRRUUUUUUR",
    // [Length: 56] Source: [Cfg2]
    12: "DDDDRRRRUUUUUUUURRRRDDDDLLLLLLLDLDDDRRRRUUUUUUUURRRRDDDD",
    // [Length: 80] Source: [Cfg2] - 步数相同，选低权重
    13: "DDDDRRRLLLUUUUUUUURRRRLRUDRRRLLLDUDDDDDDDDRRRRUUUUUUUUUUULLLLDDDLLLLDDDDRRRRRRRR",
    // [Length: 46] Source: [Cfg2]
    14: "RRRRLRUURRRLRUDRRRURDDRUUDDLLRDLLDDRLDULDLLLLL",
    // [Length: 74] Source: [Cfg2]
    15: "RRULUUUUULDDRRURURLDDRRRDDDLUURRRDDLDLLUURRUUUUDLLLLDDLUURLLDDRRDDULDLDL",
    // [Length: 81] Source: [Cfg2] - 比 Cfg1 短 (81 vs 83)
    16: "DDDDDLURRLLULUULLUURRDRRURUUUULDRURDDLDDDLLLRRRRRRRURRDDLLDDLLDDULLULDLRURDRRURDR",
    // [Length: 124] Source: [Cfg2] - 仅 Cfg2 解出
    17: "RDRRRURLDLLLUULUUULDRRUUULDRRRRRUURUUURRRRDRULLLLLDDDRRRRDRLDULRUDRDLLUULLLUUULLLDLLURRRRRRRRDULLLDDDLLDLLLDDLDDDDRDRRRURRRR",
    // [Length: 76] Source: [Cfg2]
    18: "RRLUURRRRRRDDDDLLLLLLUURRRRRRRRRRRUUUUUULLLDDDRRULURLDRDLLUUURRRDDDDDDLLDDDR",
    // [Length: 54] Source: [Cfg2] - 仅 Cfg2 解出
    19: "LLLUUUUUDDRRLLUUUUUURRRRRRDDDDDUULLLLLRRDDDRRRDDDLLLDD",
    // [Length: 75] Source: [Cfg2]
    20: "URRRRRRRRUURRUUUUURRDDDDDDLLLLUUUUULLLLLLLLURRDDDDDRUUDDRUUUUURRDDDDDDDDRRR",
    // [Length: 112] Source: [Cfg2] - 仅 Cfg2 解出
    21: "DRRLLLDDDUUULLLLLULRURRDURRUURDDDRRRRRRLLLLUURRRULUURRDLDRLDRLLLLDDRRRLLLDULLDDDUUURRDDDUUUUURRRLLLLLUUUUDULUULL",
    // [Length: 181] Source: [Cfg2] - 比 Cfg1 短
    22: "UUUUURRDURRRLLDUDULDDRRDDLRULUURUUURRRRRUURUURDDRUULLLLDLLLLLLLLDDDRRDDRRRLULLLULUUURRRRRRRRRDDDRDDDDDLUUULDDDRRRULDDUUUURDULUULLLLRRRUULLLULLLLLLDDDDDDRURDULDRLDULURRRRRLLLLDRLDDLD",
    // [Length: 68] Source: [Cfg2]
    23: "UULUUULRRLRURRRRDULLDDDDLUURUURDLLLDULLLLLLLUDULURRRRDLDDUDRDLLLLUUL",
    // [Length: 228] Source: [Cfg3] - 仅 Cfg3 解出 (超难关卡)
    24: "DDDDDDRLUURRRLLLDDRRRLLLUUUUUURRRRRRRRRDDDDDDLLLLUURUUUULLULRUUUDDDRDLLLLLDDRLDDDDRRLLUURRLLDDRRLLUUUURRRRUURRDDDDLDDRRLUUUUUULULDULRUULUUURRLRUDRRDDDLDDRDRRRUUDDLLLLLLLLUUDDDDDDDDRRLLUUUUUURRRRRRRRRRRRULLLUULDDDDDLLLLLLLLUUUUDDDDRRRRRRRR",
    // [Length: 168] Source: [Cfg2] - 仅 Cfg2 解出
    25: "DDDDUUUULLDDDDDDDURRDDDDDDLLUUUUDULLUUUUUUUULLDDDUUURRRRRRRRDDUURRDDDDDDDDDDDUUUUUUUUUUURRDDDDDDDDDDDDUUUUULLLLDDDDDUUUUUUUUUUUULLLLLLDDDDDDDDDDDDUUUUUUUUUUUULLDDDDDDDDDDDD",
    // [Length: 92] Source: [Cfg2]
    26: "LDDRRDUDRLDDLLLULLLLLLLDDDDDDRRRUDRUULRURRRRRLLLLLLDULURRLLDRDDDRUDRLRRRLLLRRRLLLRLDDLULLLUL",
    // [Length: 94] Source: [Cfg2]
    27: "LLLLLUUDULRUDRRRRRRRRRRDDLLLLUULLLLLLDULLLUURRRUUUURRRRRRRRRRDDDLLLULDDLUUDDRRLULLLLDDDUDRRRRR",
    // [No Solution] 所有配置均未解出，可能是死局或需要更高节点上限
    28: "",
    // [Length: 82] Source: [Cfg2]
    29: "LLDUDDDDDRRRRRRRRUUUDLLLLLLLLLLUDLLUUUUDDDDRRUUUDDDRRUUURRURRDDRLDDDDRRRRUUUULRUUU",
  },
  egg: {
    // [Length: 26] Source: [Cfg2]
    0: "DLLDDDDDDRUUURDRURDDDLULDU",
    1: "DLLDLDRLDRLDRDRRRRRLRULLLLLDLDRLDRLDRLDDR", // Cfg2: 41 chars, Cfg1: 41, Cfg3: 41. (Correction: Cfg1 has extra chars? No, Cfg2 is 41).
    // [Length: 66] Source: [Cfg1] - Cfg2 未解出
    2: "DDDRDDRRRUDRULLLURUURLDRLRLUURRRDDLLRLDULUULLDDLDDDLULLDRDLDRRRURD",
    // [Length: 72] Source: [Cfg2] - 远短于 Cfg3 (116)
    3: "LUDDURULRLDULLURRUDRRUDRRDRRURDDDDDLRLDULRLDDLLLDULLDDLLDLUDULRUURUURURR",
    // [No Solution]
    4: "",
    // [No Solution]
    5: "",
    // [No Solution]
    6: "",
    // [Length: 98] Source: [Cfg1]
    7: "UURLDDRRRRRRRRRRUDRRUUUUUUUUUULLLLLLLLDDDURRDDLLDDRRUDRRUUUURRDDDDDDLLUDLLLLLLUUUUUUUUUURRRRRRRRRR",
    // [Length: 142] Source: [Cfg2] - 略短于 Cfg1 (146)
    8: "RRUUUUUULLUUUURRRRRRDDLLLLLLDDDDDDDDRRRRUUUUUULRRRUDRLDDDURRRRRRUULRUUUUUULLLLDDDDDDRRUUUUUULLLLDURRRRRRDDDDDDDDDDLLLLLLDDRRRRRRUUUUUUUUUUUU",
    // [Length: 112] Source: [Cfg2]
    9: "URRLLUUUUDDDDRRRLLDDRDRRDULLDDDUUURRDDDDUUUUURRDDDDUUUULLLLLUURRRRLLLLDDLLDDULLDDDUUURRDDDUUULLLLDDDUUURRRURUULL",
    // [Length: 157] Source: [Cfg2]
    10: "LLLDLULLLLLLLDDULLDDDDDRLDDRRRRRUUUDLLLUUURRRUUULLLDLLDDDDDDDDRRDDRRRDRRRRUUUUUUUUURDDDDDDDDDRRRUUUUUUUULLLLLLURRRRRRUUULLLLLLLLLLLDLLDDDDDDDDRRDDRRRDRUDULRUURRRRRULLLLL",
    // [Length: 77] Source: [Cfg1]
    11: "DDULUURRDDDDDDRRLLDLDLDDLLULULULDLUULLDRDLDRRRDRRUUUURRRUURRLDDRULRUDRRDDDLLL",
    // [Length: 73] Source: [Cfg2] - 比 Cfg1/3 短
    12: "URURRUURUUULLULDDRDLLLLLLULUURDRDDDRUUUUUULDDLULURUULLDLLDDLDDDDDDDRRRDDR",
    // [Length: 115] Source: [Cfg2]
    13: "DRRRRDDDDRRDDDDDLLLLLUULLLLLUUUULLUUUUURRRRRDDRDDRDLLULDDDRURRURDDLLDDRRRRUUUURRUUUUULLLLLDDLLLLLDDDDLLDDDDDRRRRRUR",
    // [Length: 122] Source: [Cfg2] - 仅 Cfg2 解出
    14: "UURRRLDDRLUULLDDDDRRRRRDDLLLLLLLLLLUURUDRUUULLUURRRRDRRDDDDDLDLLLUUUUUUUURRRRURRUUULLLLDLULDDRRRUDRUDRUDRRRURRDDURURRDDDLL",
    // [No Solution]
    15: "",
    // [No Solution]
    16: "",
    // [No Solution]
    17: "",
    // [No Solution]
    18: "",
    // [No Solution]
    19: "",
  }
};